version: "3.9"

services:
  db:
    image: postgres:16
    container_name: virt-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virt
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virt-api
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/virt?sslmode=disable
      HTTP_ADDR: :8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
